/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QdbToI2Z4Lz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogContent, Dialog } from "@/components/ui/dialog"
import { Textarea } from "@/components/ui/textarea"

export function Review({openReview, setOpenReview}) {
  return (
    <Dialog  >
      <DialogTrigger asChild>
        <Button variant="outline">Leave a Review</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Leave a Review</DialogTitle>
          <DialogDescription>Share your thoughts and feedback with us.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <Textarea className="resize-none" maxLength={250} placeholder="Write your review here..." />
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              <span className="font-medium">0</span>
              /250 characters{"\n                      "}
            </p>
            <Button disabled type="submit">
              Submit Review
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
